</mkconfig

DISBIN = /dis

TARG=\
	docmd.dis

</mkfiles/mkdis

demo:V: all
	ls
	dir = `{pwd}
	echo '=== start ==='
	@{pctl forkns;
		docmd -D -n ./namespace /dis/touch.dis /test;
		# Drop commands here to play inside the namespace sandbox
		# Try to run unmount(1) and then ls(1)! What happens?
	}
	echo '=== done ==='
	ls
